name: Deploy to App Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # <- required for OIDC
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password | docker login \
        --username AWS \
        --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build and push Docker image
      env:
        IMAGE: ${{ secrets.ECR_REPO_URI }}:latest
      run: |
        docker build -t $IMAGE .
        docker push $IMAGE

    # automatically trigger App Runner to pull the new image
    - name: Deploy new image to App Runner
      run: |
        aws apprunner start-deployment --service-arn "$(aws apprunner list-services --query 'ServiceSummaryList[?ServiceName==`engageiq-demo-backend`].ServiceArn' --output text)"
